logs:
  - name: root
    level: DEBUG
    formatter: "[%d] [%t-%F] [%p] [%f:%l] %m%n"
    appender:
      - type: 1
      - type: 2
        level: DEBUG
        file: ./logs/sftest_root_log.txt
  - name: system
    level: DEBUG
    formatter: "[%d] [%t-%F] [%p] [%f:%l] %m%n"
    appender:
      - type: 1
      - type: 2
        file: ./logs/sftest_system_log.txt

system:
  port: 9191
  name: "system name"

  
test:
  int_val: 10
  int_vec: 
    - 111
    - 222
    - 333
  int_list: [100, 200, 300]
  int_set: [500, 510, 550, 500]
  int_map:
    k1: 1000
    k2: 2000

  class:
    goods:
      name: "g1"
      num: 1
      price: 2

    goods_map:
      gmk1:
        name: gmmmmk1
        num: 10
        price: 20
      gmk2:
        name: gmmmmk2
        num: 11
        price: 222

    goods_map_list:
      listgmk1:
        - name: listgmmmmk1
          num: 100
          price: 200
        - name: listgmmmmk2
          num: 111
          price: 2222
    